verbose: True
model_name: monodepth2
data:
  config: '/app/kiti.dataset'
  dataset:
    directory: '/app/data'
    directory_train: '/app/data/train'
    directory_test: '/app/data/test'
    archive:
      name: data_depth_annotated
      ext: zip
      store_path: /app/data/archive
      train_path: train
      test_path: val
